# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-vue:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:14
  script:
    - cd final-pjt-front
    - npm install
    - npm run build
  artifacts:
    paths:
      - final-pjt-front/dist/

build-django:       # This job runs in the build stage, which runs first.
  stage: build
  image: python:3.12
  script:
    - cd final-pjt-back
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
  artifacts:
    paths:
      - final-pjt-back/staticfiles/

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: ruby:2.7
  script:
    - apt-get update -y
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 43.200.128.146 >> ~/.ssh/known_hosts
    - scp -r final-pjt-front/dist/* ubuntu@43.200.128.146:/home/ubuntu/final-pjt/final-pjt-front/
    - scp -r final-pjt-back/staticfiles/* ubuntu@43.200.128.146:/home/ubuntu/final-pjt/final-pjt-back/staticfiles/
  only:
    - master  # master 브랜치에 푸시할 때만 배포
