# Generated by Django 4.2.16 on 2024-11-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_userproducts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='fin_prdt_cd',
            field=models.CharField(max_length=255),
        ),
    ]
