# Generated by Django 4.2.16 on 2024-11-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_users',
        ),
    ]
